//////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) GBS 2012 All Right Reserved, http://gbs-jsc.com.                   //
// This source is subject to the GBS Permissive License. Please see the License.txt //
// file for more information.                                                       //
//                                                                                  //
// file: GEvents.hpp                                                                //
//////////////////////////////////////////////////////////////////////////////////////

#ifndef GEVENTS_HPP_
#define GEVENTS_HPP_

#define GEVENT_DVBPLAY_EVENT_BASE     0xF100 // 61696
#define GEVENT_KEY_EVENT_BASE         0xFE00 // 65024
#define GEVENT_BIZ_EVENT_BASE         0xFE80 // 65152
#define GEVENT_UI_CONTROL_BASE        0xFEF0 // 65264
#define GEVENT_MAX                0xFFFFFFFF

#define ADD_EVENT_LISTENER(EVTID, PDELEGATE, CLASS, OBJ, METHOD)\
   PDELEGATE = DELEGATE(CLASS, OBJ, METHOD);\
   this->addEventListener(EVTID, PDELEGATE);

#define REMOVE_EVENT_LISTENER(EVTID, PDELEGATE)\
   this->removeEventListener(EVTID, PDELEGATE);

typedef enum GEvents_e
{
   //61696 - DVBPlay_Event
   GEVENT_DVBPLAY_NO_CHANNEL = GEVENT_DVBPLAY_EVENT_BASE,
   GEVENT_DVBPLAY_NO_SIGNAL,
   GEVENT_DVBPLAY_SIGNAL_FOUND,
   GEVENT_DVBPLAY_TUNER_LOCK,
   GEVENT_DVBPLAY_SCAN_START,
   GEVENT_DVBPLAY_SCAN_CHANNEL_FOUND,
   GEVENT_DVBPLAY_SCAN_ERROR,
   GEVENT_DVBPLAY_SCAN_STOPED,
   GEVENT_DVBPLAY_SCAN_COMPLETE,
   GEVENT_DVBPLAY_SCAN_CHANGE_DVBPARA,
   GEVENT_DVBPLAY_SCAN_CHANGE_FREQ,
   GEVENT_DVBPLAY_SCAN_TYPE,
   GEVENT_DVBPLAY_EPG_FOUND,
   GEVENT_DVBPLAY_TUNER_HWFAIL,
   GEVENT_DVBPLAY_SIGNAL_STATUS,
   GEVENT_DVBPLAY_STORAGE_LOW_WARNING,
   GEVENT_DVBPLAY_STORAGE_FULL_WARNING,
   GEVENT_DVBPLAY_RECORD_WRITE_ERROR,
   GEVENT_DVBPLAY_DECODING_ERROR,
   GEVENT_DVBPLAY_UNSUPPORTED_STREAM,
   GEVENT_DVBPLAY_UNSUPPORTED_VIDEO_CODEC,
   GEVENT_DVBPLAY_UNSUPPORTED_AUDIO_CODEC,
   GEVENT_DVBPLAY_PLAY_READ_ERROR,
   GEVENT_DVBPLAY_COMMAND_COMPLETED,

   //65024 - Keys_Event
   GEVENT_KEY_PRESSED = GEVENT_KEY_EVENT_BASE,

   GEVENT_KEY_EVENT_MAX,

   //65152 - Business events
   // Usb events
   GEVENT_USB_EVENT_PLUGGED = GEVENT_BIZ_EVENT_BASE,
   GEVENT_USB_EVENT_UNPLUGGED,
   GEVENT_USB_EVENT_MOUNTED,
   GEVENT_USB_EVENT_UNMOUNTED,
   GEVENT_USB_EVENT_CONNECTION_LOST,

   // Dvr events
   GEVENT_DVR_START_RECORD,
   GEVENT_DVR_STOP_RECORD,
   GEVENT_DVR_START_PLAYBACK,
   GEVENT_DVR_STOP_PLAYBACK,
   GEVENT_DVR_ROUTINE_PLAYBACK,
   GEVENT_DVR_ROUTINE_RECORD,
   GEVENT_DVR_PLAYREC_STAGE_CHANGED,
   GEVENT_DVR_PLAYREC_END_OF_FILE,
   GEVENT_DVR_PLAYREC_END_OF_PLAYBACK,
   GEVENT_DVR_PLAYREC_END_OF_PLAYBACK_GUI,
   GEVENT_DVR_FILE_OPERATION_COMPLETE,

   GEVENT_BIZ_EVENT_MAX,

   //65264 - UI_Control_Event
   GEVENT_FOCUS_CHANGED = GEVENT_UI_CONTROL_BASE,
   GEVENT_SELECT_CHANGED,
   GEVENT_ENABLE_CHANGED,
   GEVENT_BUTTON_PRESSED,

   GEVENT_LIST_ITEM_SELECT,
   GEVENT_LIST_ITEM_FOCUSED,
   GEVENT_LIST_ITEM_UNFOCUSED,
   GEVENT_LIST_UNFOCUSED,
   GEVENT_LIST_REFRESH_DONE,

   GEVENT_TIMER_TRIGGER,
   GEVENT_FINISH_SAVE_DATA,
   GEVENT_CHANGE_FAV_GROUP,
   ON_CLOSE_FORM_MORALITY,
   GEVENT_TIMEDISPSETTING_FINISHED,
   GEVENT_TRANSSETTING_FINISHED,
   GEVENT_TIMEZONESETTING_FINISHED,
   GEVENT_SELECTCHANNEL_FINISHED,
   GEVENT_SELECTPIPOUTPUT_FINISHED,
   GEVENT_SELECTPIPPOS_FINISHED,
   GEVENT_CLOSE_FORM_DISPLAYSETTINGLIST,
   GEVENT_SELECT_TVSTANDARD_FINISHED,
   GEVENT_SELECT_ASPECTRATIO_FINISHED,
   GEVENT_SELECT_VIDEOFORMAT_FINISHED,
   GEVENT_SELECT_TVRESOLUTION_FINISHED,
   GEVENT_SELECT_ERROR_RECOVERY_FINISHED,
   ON_CLOSE_FORM_RFSIGNAL,
   ON_CLOSE_FORM_RFCCHANNEL,
   ON_CLOSE_FORM_UPGRADE_FIRMWARE,
   ON_CLOSE_FORM_DISPLAY_LANGUAGE_LIST,
   ON_CLOSE_FORM_LANGUAGE,
   ON_CLOSE_FORM_LANGUAGE2,
   ON_CLOSE_FORM_SUBTITLE,
   ON_CLOSE_FORM_LANGUAGE_SUBTITLE,
   ON_CLOSE_FORM_LANGUAGE_SUBTITLE2,
   GEVENT_UI_CONTROL_MAX,
   GEVENT_AUTHEN_PASSWORD_REQUEST,
   GEVENT_AUTHEN_PASSWORD_PLAY_CHANNEL_DONE,
   GEVENT_AUTHEN_PASSWORD_PLAY_CHANNEL_EX_DONE,
   GEVENT_AUTHEN_PASSWORD_OPEN_FORM_DONE,
   GEVENT_AUTHEN_PASSWORD_SETTING_DONE,
   GEVENT_AUTHEN_PASSWORD_STARTUP_LOGIN_DONE,
   GEVENT_CREATE_PARENTAL_CODE_SUCCESS,//event da dc dung trong FormParentalControl, k dc su dung lai.
   GEVENT_CLOSE_FORM_UNCORRECT_PASSWD,
   GEVENT_CLOSE_FORM_FREQ,
   GEVENT_CLOSE_FORM_SYMBOL,
   GEVENT_CLOSE_FORM_ADDTRANSPONDER,
   GEVENT_CLOSE_FORM_SHOW_CURRENT_VERSION_MESS,
   ON_CLOSE_FORM_LNBSIGNAL,
   ON_CLOSE_FORM_TPLIST,
   GEVENT_SORT_CHANNEL_LIST,
   GEVENT_TMD_UPDATE_DATE,
   GEVENT_TMD_UPDATE_TIME,
   GEVENT_TMD_UPDATE_TIMER_LIST,
   GEVENT_ON_CLOSE_TIMER_MANAGER,
   GEVENT_CLOSE_COMBINE_KEY_FORM,
   GEVENT_SHOW_FORM_CHANNEL_INFO,
   GEVENT_GOT_EPG_DATA,
   GEVENT_PLAY_LOCKED_CHANNEL,
   GEVENT_REMOVE_ONE_RECORD_TIMER,
   GEVENT_EXECUTE_STANDBY,
   GEVENT_RETUNE_TUNER,
   GEVENT_EXECUTE_ALARM,
   GEVENT_ENTER_ALARM,
   GEVENT_EXIT_ALARM,
   GEVENT_STOP_TIMER_CHECK_ALARM,
   GEVENT_GOT_BROADCAST_TIME,
   //GEVENT_SWITCH_TO_EPG_FULL,
   //GEVENT_SWITCH_TO_EPG_ONE
   GEVENT_REMOVE_ALL_RECORD_TIMER,
   GEVENT_REQUEST_PLAY_CHANNEL,
   GEVENT_FINISH_WRITING_DATA_TO_FLASH,
   GEVENT_SHOW_RADIO_TITLE,
   GEVENT_RETUNER_CURR_DVBPARA,

   GEVENT_ON_PLAY_CHANNEL_SUCCESS, // ChannelListData dispatch event nay sau khi playChannel success
   GEVENT_DRAW_VIEW,
   GEVENT_GUI_UPDATE_FIRMWARE_FINISH,
   GEVENT_GUI_STARTUP_FINISH,
   GEVENT_FLUSH_ERR_MESSAGE,

   // PIP events
   GEVENT_PIP_COMMAND_DONE,

   GEVENT_UPDATE_LOCK_CHANNEL,

   // Common form: Input Text
   GEVENT_UPDATE_TEXT_DONE,

   // Game events
   GEVENT_GAME_SETTING_DONE,
   GEVENT_GAME_PAUSE,
   GEVENT_CHESS_WIN,
   // Teletext / Subtitle
   GEVENT_TTX_UPDATE,
   GEVENT_SUBT_START,
   GEVENT_SUBT_STOP,

   GEVENT_UPDATE_VOLUME,
   GEVENT_BACKUP_USERDATA_DONE,
   GEVENT_RESTORE_CHANNEL_LIST,
   GEVENT_IMAGE_OPEN_FILE,

   GEVENT_NONE = GEVENT_MAX,
}
GEvents;

//namespace GBS {
//namespace STM {
//namespace Framework {
//////////////////////////////////////////////////////////////////////////////////////
// ! Dummy
//////////////////////////////////////////////////////////////////////////////////////
//} //Framework
//} //STM
//} //GBS
#endif /* GEVENTS_HPP_ */
