//////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) GBS 2012 All Right Reserved, http://gbs-jsc.com.                   //
// This source is subject to the GBS Permissive License. Please see the License.txt //
// file for more information.                                                       //
//                                                                                  //
// file: GLanguage.hpp                                                              //
//////////////////////////////////////////////////////////////////////////////////////

#ifndef GLANGUAGE_HPP_
#define GLANGUAGE_HPP_

#include "GDebug.hpp"

typedef enum Language_e
{
   VN,
   EN,
   // insert more language here
   // always put this at the bottom
   LANGUAGE_COUNT
}
GLanguage_t;

typedef enum Language_Item_Index_e
{
   _L_OK,
   _L_CANCEL,
   _L_CANCEL1,
   _L_YES,
   _L_NO,
   _L_DENY,
   _L_DENY1,
   _L_IGNORE,
   _L_DVBS,
   _L_GUIDE_BACK_TO_MENU,
   _L_ON,
   _L_OFF,
   _L_LOCK,
   _L_UNLOCK,
   _L_AUTO,
   _L_RESET,
   _L_WATTING,
   _L_SAVE,
   _L_SAVING,
   _L_LOCKUNLOCK,
   _L_DEFAULT,
   _L_PRESS_OK,

   //GUIDE
   _L_GUIDE_DELETE,
   _L_GUIDE_DELETE_ALL,
   _L_GUIDE_SPACE,
   _L_GUIDE_EXIT,
   _L_GUIDE_SORT,
   _L_GUIDE_SORT_AZ,
   _L_GUIDE_SORT_ZA,
   _L_GUIDE_FIND,
   _L_GUIDE_ADD,
   _L_GUIDE_MOVE,
   _L_GUIDE_ADD_SYMBOL,

   //COMMON
   _L_CYCLE,
   _L_CYCLE_ONCE,
   _L_CYCLE_DAILY,
   _L_CYCLE_WEEKLY,
   _L_MODE,
   _L_MODE_ALARM,
   _L_MODE_STANDBY,
   _L_MODE_RECORD,
   _L_MODE_NOT_DEFINED,
   _L_NO_CHANNEL,
   _L_NO_SIGNAL,
   _L_NO_AUDIO,
   _L_SCRAMBLE_CHANNEL,
   _L_SIGNAL_NOT_GOOD,

   //MAIN MENU
   _L_MAIN_MENU_CHANNEL_MANAGER,
   _L_MAIN_MENU_CHANNEL_MANAGER_CHANNEL_LIST,
   _L_MAIN_MENU_CHANNEL_MANAGER_EDIT_FAV_CHANNELS,
   _L_MAIN_MENU_CHANNEL_MANAGER_PIP_DUAL_TV,
   _L_MAIN_MENU_INSTALLATION,
   _L_MAIN_MENU_INSTALLATION_CHANNEL_SEARCH,
   _L_MAIN_MENU_INSTALLATION_AUTO_SEARCH,
   _L_MAIN_MENU_INSTALLATION_MANUAL_SEARCH,
   _L_MAIN_MENU_INSTALLATION_TRANSPONDER_LIST,
   _L_MAIN_MENU_INSTALLATION_FACTORY_RESET,
   _L_MAIN_MENU_INSTALLATION_DECODER_INFO,
   _L_MAIN_MENU_INSTALLATION_VIEWING_CARD,
   _L_MAIN_MENU_YOUR_PREFERENCES,
   _L_MAIN_MENU_YOUR_PREFERENCES_LANGUAGE_SETTING,
   _L_MAIN_MENU_YOUR_PREFERENCES_TV_SETTINGS,
   _L_MAIN_MENU_YOUR_PREFERENCES_PARENTAL_CONTROL,
   _L_MAIN_MENU_YOUR_PREFERENCES_DISPLAY_SETTING,
   _L_MAIN_MENU_YOUR_PREFERENCES_TIMER_MANAGER,
   _L_MAIN_MENU_MAIL_BOX,
   _L_MAIN_MENU_UTILITIES,
   _L_MAIN_MENU_GAMES_GSNAKE,

   // Utilities
   _L_UTILITIES_MEDIA,
   _L_UTILITIES_IMAGE,
   _L_IMAGE_UNABLE_OPEN_FILE,
   _L_GAMES_HIGHSCORE,
   _L_GAMES_SETTING,
   _L_GAMES_GUIDE_SPEED,
   _L_GAMES_GUIDE_MODE,
   _L_GAMES_GUIDE_MODE_DETAIL_1,
   _L_GAMES_GUIDE_MODE_DETAIL_2,
   _L_GAMES_SETTING_SPEED_LOW,
   _L_GAMES_SETTING_SPEED_MED,
   _L_GAMES_SETTING_SPEED_HI,
   _L_GAMES_SETTING_MODE_NONE,
   _L_GAMES_SETTING_MODE_MAPS,
   _L_GAMES_GUIDE_PAUSE,
   _L_GAMES_GUIDE_CHANGE_PAGE,
   _L_GAMES_ERR_NO_RECORD,

   _L_GAMES_SUDOKU,
   _L_GAMES_LEVEL_TITLE,
   _L_GAMES_TIMER_TITLE,
   _L_GAMES_NEW_PUZZLE_TITLE,
   _L_GAMES_EASY,
   _L_GAMES_MEDIUM,
   _L_GAMES_HARD,
   _L_GAMES_CLEAR,
   _L_GAMES_REPLAY,
   _L_GAMES_CONGRATULATION,
   _L_GAMES_SOLVED,

   _L_GAMES_LINE,
   _L_GAMES_LINE_NEXT,
   _L_GAMES_LINE_BALL,
   _L_GAMES_LINE_SCORE,
   _L_GAMES_LINE_MOVE_SELECT,
   _L_GAMES_LINE_GAME_OVER,

   _L_GAMES_CHINESECHESS,
   _L_GAMES_COMPUTER_WIN,
   _L_GAMES_HUMAN_WIN,
   _L_GAMES_COMPUTER_MOVE,
   _L_GAMES_HUMAN_MOVE,

   _L_GAMES_SOKOBAN,
   _L_GAMES_SOKOBAN_PUSH,
   _L_GAMES_SOKOBAN_NEXT_LEVEL,
   _L_GAMES_SOKOBAN_UNDO,

   //FormDisplaySetting
   _L_FORM_DISPLAY_SETTING_TITLE,
   _L_FORM_DISPLAY_SETTING_DISPLAY_TRANSPARENCY,
   _L_FORM_DISPLAY_SETTING_CHANNEL_BANNER_TIMEOUT,
   _L_FORM_DISPLAY_SETTING_TIME_ZONE,
   _L_FORM_DISPLAY_SETTING_ALWAYS,

   //FormLanguageSetting
   _L_FORM_LANGUAGE_SETTING_LANGUAGE_SETTING_TITLE,
   _L_FORM_LANGUAGE_SETTING_MENU_LANGUAGE,
   _L_FORM_LANGUAGE_SETTING_AUDIO_LANGUAGE,
   _L_FORM_LANGUAGE_SETTING_SUBTITLE,
   _L_FORM_LANGUAGE_SETTING_SUBTITLE_LANGUAGE,
   _L_FORM_LANGUAGE_SETTING_VIETNAMESE,
   _L_FORM_LANGUAGE_SETTING_ENGLISH,
   _L_FORM_LANGUAGE_SETTING_FIRST_LANGUAGE,
   _L_FORM_LANGUAGE_SETTING_SECOND_LANGUAGE,
   _L_FORM_LANGUAGE_SETTING_TELETEXT,
   _L_FORM_LANGUAGE_SETTING_TELETEXT_LANGUAGE,

   //Form Default Setting
   _L_FORM_DEFAULT_SETTING_CONFIRM,
   _L_FORM_DEFAULT_SETTING_WARNING,
   _L_FORM_DEFAULT_SETTING_WAITING,

   //Form Letter Box
   _L_FORM_LETTER_BOX_TITLE,
   _L_FORM_LETTER_BOX_MESS,

   //Form Parental Control
   _L_FORM_PARENTAL_CONTROL_TITLE,
   _L_FORM_PARENTAL_CONTROL_MORALITY_LEVEL,
   _L_FORM_PARENTAL_CONTROL_DECODER_LOCK,
   _L_FORM_PARENTAL_CONTROL_CHANNEL_LOCK,
   _L_FORM_PARENTAL_CONTROL_CHANGE_PARENTAL_CODE,
   _L_FORM_PARENTAL_CONTROL_UNDER_10_AGE,
   _L_FORM_PARENTAL_CONTROL_UNDER_12_AGE,
   _L_FORM_PARENTAL_CONTROL_UNDER_16_AGE,
   _L_FORM_PARENTAL_CONTROL_UNDER_18_AGE,

   //Form Change password
   _L_FORM_CHANGE_PASSWORD_CREATE_PARENTAL_CODE,
   _L_FORM_CHANGE_PASSWORD_CONFIRM,

   //Form Notification Change Password
   _L_FORM_NOTIFICATION_PASSWORD_CHANGED_SUCCESS,
   _L_FORM_NOTIFICATION_PASSWORD_CHANGED_FAIL,

   //Form Authentication of Password
   _L_FORM_AUTHEN_PASSWORD_ENTER_PASSWORD,
   _L_FORM_AUTHEN_PASSWORD_RETRY,
   _L_FORM_AUTHEN_PASSWORD_TITLE_SYSTEM_SETTING,

   //Form SetTopBox info
   _L_FORM_DECODER_INFORMATION_TITLE,
   _L_FORM_DECODER_INFORMATION_MODEL_NAME,
   _L_FORM_DECODER_INFORMATION_SOFTWARE_VERSION,
   _L_FORM_DECODER_INFORMATION_LOADER_VERSION,
   _L_FORM_DECODER_INFORMATION_DECODER_CA_SN,
   _L_FORM_DECODER_INFORMATION_CAK_VERSION,
   _L_FORM_DECODER_INFORMATION_SOFTWARE_STATE,
   _L_FORM_DECODER_INFORMATION_PROJECT_INFORMATION,
   _L_FORM_DECODER_INFORMATION_DECODER_SERIAL_NUMBER,
   _L_FORM_DECODER_INFORMATION_USAGE_ID,
   _L_FORM_DECODER_INFORMATION_LAST_UPDATE,
   _L_FORM_DECODER_INFORMATION_GUIDE_UPDATE_SOFTWARE,
   _L_FORM_DECODER_INFORMATION_GUIDE_UPDATE_SOFTWARE_USB,
   _L_FORM_DECODER_INFORMATION_SOFTWARE_STATE_MANUFACTURE,
   _L_FORM_DECODER_INFORMATION_SOFTWARE_STATE_DECLARATION,
   _L_FORM_DECODER_INFORMATION_SOFTWARE_STATE_REGISTRATION,
   _L_FORM_DECODER_INFORMATION_SOFTWARE_STATE_UNKNOWN,

   //TV Settings
   _L_FORM_TV_SETTINGS_TITLE,
   _L_FORM_TV_SETTINGS_TV_STANDARD,
   _L_FORM_TV_SETTINGS_TV_RESOLUTION,
   _L_FORM_TV_SETTINGS_ERR_RECOVERY,
   _L_FORM_TV_SETTINGS_SCREEN_RATIO,
   _L_FORM_TV_SETTINGS_ASPECT_CONVERSION,
   _L_FORM_TV_SETTINGS_DIGITAL_DOLBY,
   _L_FORM_TV_SETTINGS_RF_OUTPUT,
   _L_FORM_TV_SETTINGS_RF_CHANNEL,
   _L_FORM_TV_SETTINGS_ADJUST_VIDEO,
   _L_FORM_TV_SETTINGS_LCN,
   _L_FORM_TV_SETTINGS_ANTENPOWER,
   _L_FORM_TV_SETTINGS_SHORT_CIRCUIT,
   _L_FORM_TV_SETTINGS_FREQUENCY_MODE,
   _L_FORM_TV_SETTINGS_AUTOSCAN_MODE,
   _L_FORM_TV_SETTINGS_CONTROL_VOLUME,

   //HDTV Resize
   _L_FORM_HDTV_RESIZE_LETTER_BOX,
   _L_FORM_HDTV_RESIZE_PAN_SCAN,
   _L_FORM_HDTV_RESIZE_COMBINED,

   //VideoControl
   _L_VIDEO_CONTROL_TITLE,
   _L_VIDEO_CONTROL_BRIGHTNESS,
   _L_VIDEO_CONTROL_COLOR,
   _L_VIDEO_CONTROL_CONTRAST,
   _L_VIDEO_CONTROL_DISPLAY_TRANSPARENCY,
   _L_VIDEO_CONTROL_ERR_RECOVERY_HIGH,
   _L_VIDEO_CONTROL_ERR_RECOVERY_FULL,

   //Form Channel List
   _L_FORM_CHANNEL_LIST_TITLE,
   _L_FORM_CHANNEL_LIST_TV_ALL,
   _L_FORM_CHANNEL_LIST_ENTER_NAME,
   _L_FORM_CHANNEL_LIST_GUIDE_FREE,
   _L_FORM_CHANNEL_LIST_COPY,
   _L_FORM_CHANNEL_LIST_PASTE,
   _L_FORM_CHANNEL_LIST_SORT_AND_PASTE,
   _L_FORM_CHANNEL_LIST_OK_EXIT,
   _L_FORM_CHANNEL_LIST_EDIT,
   _L_FORM_CHANNEL_LIST_DELETE,
   _L_FORM_CHANNEL_LIST_GUIDE_SCRAMBLE,
   _L_FORM_CHANNEL_LIST_GUIDE_ALL,
   _L_FORM_CHANNEL_LIST_GUIDE_STRING_SEARCH,
   _L_FORM_CHANNEL_LIST_TITLE_SORT,
   _L_FORM_CHANNEL_LIST_BACKUP_RESTORE,
   _L_FORM_CHANNEL_LIST_BACKUP_DATA,
   _L_FORM_CHANNEL_LIST_RESTORE_DATA,
   _L_FORM_CHANNEL_LIST_RESTORE_DATA_BY_USB,
   _L_FORM_CHANNEL_LIST_BACKUP_DATA_DONE,
   _L_FORM_CHANNEL_LIST_RESTORE_DATA_DONE,

   _L_FORM_CHANNEL_LIST_EDIT_CHANNEL_NUMBER,
   _L_FORM_EDIT_CHANNEL_NUMBER_CURRENT,
   _L_FORM_EDIT_CHANNEL_NUMBER_NEW,

   //Form show error lock channel mess
   _L_FORM_SHOW_LOCK_CHANNEL_ERROR_MESS1,
   _L_FORM_SHOW_LOCK_CHANNEL_ERROR_MESS2,

   //Form Sort Channel
   _L_FORM_SORT_CHANNEL_SORT_BY_DEFAULT,
   _L_FORM_SORT_CHANNEL_SORT_BY_Aa_Zz,
   _L_FORM_SORT_CHANNEL_SORT_BY_Zz_Aa,

   //Form Full Channel List
   _L_FORM_FULL_CHANNEL_LIST_LOCK_ERROR_MESS,

   //Form Fav List
   _L_FORM_FAVORITE_LIST_TITLE,
   _L_FORM_FAVORITE_LIST_RENAME_ERROR,
   _L_FORM_FAVORITE_LIST_1,
   _L_FORM_FAVORITE_LIST_2,
   _L_FORM_FAVORITE_LIST_3,
   _L_FORM_FAVORITE_LIST_4,
   _L_FORM_FAVORITE_LIST_5,
   _L_FORM_FAVORITE_LIST_6,
   _L_FORM_FAVORITE_LIST_7,
   _L_FORM_FAVORITE_LIST_8,

   //FORM MANAGE FAV CHANNEL
   _L_FORM_MANAGE_FAVORITE_CHANNEL_GUIDE_FAV_LIST,
   _L_FORM_MANAGE_FAVORITE_CHANNEL_GUIDE_RENAME_GROUP,
   _L_FORM_MANAGE_FAVORITE_CHANNEL_ALL_CHANNEL,
   _L_FORM_MANAGE_FAVORITE_CHANNEL_ALREADY,

   //FORM TRANSPONDER LIST
   _L_FORM_TRANSPONDER_LIST_TITLE,
   _L_FORM_TRANSPONDER_LIST_LIST_CHANNEL_TITLE,
   _L_FORM_TRANSPONDER_LIST_LIST_EDIT_TRANSPONDER,
   _L_FORM_TRANSPONDER_LIST_LIST_DELETE_TRANSPONDER,
   _L_FORM_TRANSPONDER_LIST_LIST_NEW_TRANSPONDER,

   //FORM NEW TRANSPONDER
   _L_FORM_NEW_TRANSPONDER_NEW_TP_TITLE,
   _L_FORM_NEW_TRANSPONDER_EDIT_TP_TITLE,
   _L_FORM_NEW_TRANSPONDER_FREQUENCY,
   _L_FORM_NEW_TRANSPONDER_SYMBOL_RATE,
   _L_FORM_NEW_TRANSPONDER_POLARIZATION,
   _L_FORM_NEW_TRANSPONDER_FEC,
   _L_FORM_NEW_TRANSPONDER_MODULATION,
   _L_FORM_NEW_TRANSPONDER_TRANSPONDER_EXIST,

   //FORM CHANNEL SCAN
   _L_FORM_CHANNEL_SCAN_TITLE,
   _L_FORM_CHANNEL_SCAN_TV_CHANNEL,
   _L_FORM_CHANNEL_SCAN_TV_RADIO,
   _L_FORM_CHANNEL_SCAN_CHANNEL_NUM,
   _L_FORM_CHANNEL_SCAN_SEARCH_FAIL,
   _L_FORM_CHANNEL_SCAN_SEARCH_SUCCESS,
   _L_FORM_CHANNEL_SCAN_SEARCH_CONTINUE,
   _L_FORM_CHANNEL_SCAN_SEARCH_SAVING,

   //FORM CHANNEL SCAN SETTINGS
   _L_FORM_CHANNEL_SCAN_SETTINGS_TITLE,
   _L_FORM_CHANNEL_SCAN_SETTINGS_SATELLITE,
   _L_FORM_CHANNEL_SCAN_SETTINGS_LNB_FREQUENCY,
   _L_FORM_CHANNEL_SCAN_SETTINGS_LNB_POWER,
   _L_FORM_CHANNEL_SCAN_SETTINGS_22KHZ_TONE,
   _L_FORM_CHANNEL_SCAN_SETTINGS_TRANSPONDER_LIST,
   _L_FORM_MANUAL_SCAN_SETTING_TITLE,
   _L_FORM_MANUAL_SCAN_SETTING_CHANNEL_NO,
   _L_FORM_SCAN_DVBT_FREQUENCY,
   _L_FORM_SCAN_DVBT2_FREQUENCY,
   _L_FORM_SCAN_DVBC_FREQUENCY,
   _L_FORM_MANUAL_SCAN_SETTING_SCAN_FREQUENCY,
   _L_FORM_DVBC_SCAN_SETTINGS_START_FREQUENCY,
   _L_FORM_DVBC_SCAN_SETTINGS_END_FREQUENCY,
   _L_FORM_DVBC_SCAN_SETTINGS_SYMBOL_RATE,
   _L_FORM_DVBC_SCAN_SETTINGS_MODULATION,
   _L_FORM_DVBC_SCAN_SETTINGS_NETWORK,
   _L_FORM_SCAN_SETTINGS_SYMBOLRATE_LIMIT,

   //FORM TIMER MANAGER
   _L_FORM_TIMER_MANAGER_TITLE,
   _L_FORM_TIMER_MANAGER_TIMER_LIST_TITLE,
   _L_FORM_TIMER_MANAGER_TIMER_NO_EVENT,
   _L_FORM_TIMER_MANAGER_GUIDE_EDIT_TIMER,
   _L_FORM_ADD_TIMER_TITLE,
   _L_FORM_ADD_TIMER_CHANNEL,
   _L_FORM_ADD_TIMER_DATE,
   _L_FORM_ADD_TIMER_DATE_SUN,
   _L_FORM_ADD_TIMER_DATE_MON,
   _L_FORM_ADD_TIMER_DATE_TUE,
   _L_FORM_ADD_TIMER_DATE_WED,
   _L_FORM_ADD_TIMER_DATE_THU,
   _L_FORM_ADD_TIMER_DATE_FRI,
   _L_FORM_ADD_TIMER_DATE_SAT,
   _L_FORM_ADD_TIMER_START_TIME,
   _L_FORM_ADD_TIMER_DURATION,
   _L_FORM_ADD_TIMER_SAVE_TIMER,
   _L_FORM_DELETE_TIMER_MESS_DELETE_ALL,
   _L_FORM_DELETE_TIMER_MESS_DELETE_TIMER,
   _L_FORM_SHOW_TIMER_ERROR_MESS,
   _L_FORM_SHOW_TIMER_DURATION_ERROR_MESS,
   _L_FORM_SHOW_TIMER_DATE_ERROR_MESS,
   _L_FORM_SHOW_TIMER_DAY_ERROR_MESS,
   _L_FORM_SHOW_TIMER_DUPLICATE_TIMER_ERROR_MESS,
   _L_FORM_SHOW_TIMER_OVERLAPPED_ERROR_MESS,
   _L_FORM_POPUP_EXECUTE_ALARM_MODE_TIMER_MESS,
   _L_FORM_POPUP_EXECUTE_RECORD_MODE_TIMER_MESS,
   _L_FORM_POPUP_EXECUTE_STANDBY_MODE_TIMER_MESS,
   _L_FORM_POPUP_EXECUTE_TIMER_SELECT_BUTTON_MESS,
   _L_FORM_POPUP_EXECUTE_TIMER_CONFLICT_FREQ_MESS,

   // FORM UPGRADE FIRMWARE
   _L_FORM_UPGRADE_FIRMWARE_TITLE,
   _L_FORM_UPGRADE_FIRMWARE_SATELLITE,
   _L_FORM_UPGRADE_FIRMWARE_TRANSPONDER_LIST,
   _L_FORM_UPGRADE_FIRMWARE_UPDATE_SOFTWARE,
   _L_FORM_UPGRADE_FIRMWARE_CURRENT_VERSION,
   _L_FORM_UPGRADE_FIRMWARE_WAITTINGS_USB,
   _L_FORM_UPGRADE_FIRMWARE_SUCCESS,
   _L_FORM_UPGRADE_FIRMWARE_FAILED,
   _L_FORM_UPGRADE_FIRMWARE_FAILED_FORMAT,
   _L_FORM_UPGRADE_FIRMWARE_FAILED_SIGN,

   //FORM STORAGE INFO
   _L_FORM_STORAGE_INFO_TITLE,
   _L_FORM_STORAGE_INFO_INFORM_FULL,
   _L_FORM_STORAGE_INFO_INFORM_REC_ERROR_MESSAGE,
   _L_FORM_STORAGE_INFO_INFORM_FILE_OPERATION_INPROGRESS,
   _L_FORM_STORAGE_INFO_INFORM_CANNOT_MOUNT_USB,
   _L_FORM_STORAGE_INFO_INFORM_CANNOT_DELETE_FILE,
   _L_FORM_STORAGE_INFO_INFORM_CANNOT_COPY_FILE,
   _L_FORM_STORAGE_INFO_INFORM_CANNOT_RENAME_FILE,
   _L_FORM_STORAGE_INFO_INFORM_CANNOT_STOP_RECORDING,
   _L_FORM_STORAGE_INFO_INFORM_CANNOT_STOP_PLAYING,
   _L_FORM_STORAGE_INFO_INFORM_CANNOT_START_PLAYING,
   _L_FORM_STORAGE_INFO_INFORM_CHANNEL_LOCKED,
   _L_FORM_STORAGE_INFO_INFORM_COPY_PLAYABLE_FILE_ONLY,
   _L_FORM_STORAGE_INFO_INFORM_COPY_FILE_NAME_NOT_VALID,
   _L_FORM_STORAGE_INFO_INFORM_COPY_DONE,
   _L_FORM_STORAGE_INFO_INFORM_HOT_UNPLUG_USB,
   _L_FORM_STORAGE_INFO_INFORM_FILE_NOT_SUPPORT,
   _L_FORM_STORAGE_INFO_INFORM_RECORDING_IN_PROGRESS,
   _L_FORM_STORAGE_INFO_INFORM_CHANNEL_NOT_EXIST,

   //FORM CONFIRM MESSAGE
   _L_FORM_CONFIRM_TITLE,
   _L_FORM_CONFIRM_EXIT_RECORD_MESSAGE,
   _L_FORM_CONFIRM_EXIT_PLAYBACK_MESSAGE,
   _L_FORM_CONFIRM_DELETE_FILE_MESSAGE,
   _L_FORM_CONFIRM_RENAME_FILE_MESSAGE,
   _L_FORM_CONFIRM_RENAME_FILE_AGAIN_MESSAGE,
   _L_FORM_CONFIRM_EXIT_GAME_SNAKE,
   _L_FORM_CONFIRM_RESTART_GAME_SNAKE,

   //FORM INPUT TEXT
   _L_FORM_INPUT_TITLE,
   _L_FORM_INPUT_STATIC,
   _L_FORM_INPUT_DYNAMIC,
   _L_FORM_INPUT_INFORM_TEXT_LENGTH_MAX,

   // FORM EPG ONE CHANNEL
   _L_FORM_EPG_ONE_CHANNEL_TITLE,
   _L_FORM_EPG_ONE_CHANNEL_GUIDE_EPG_TYPE,
   _L_FORM_EPG_ONE_CHANNEL_GUIDE_SAVE_TIMER,
   _L_FORM_EPG_ONE_CHANNEL_GUIDE_NEXT_DAY,
   _L_FORM_EPG_ONE_CHANNEL_GUIDE_PREVIOUS_DAY,
   _L_FORM_EPG_ONE_CHANNEL_WARNING_NO_EVENT,

   // FORM EPG ONE CHANNEL
   _L_FORM_EPG_FULL_TITLE,

   //FORM EPG FULL_TIMER MANAGER
   _L_FORM_EPG_FULL_TIMER_MANAGER_TITLE,

   //KEYBOARD
   _L_KEYBOARD_TITLE,

   //FORM_REC_PLAYBACK
   _L_FORM_PLAYBACK_FILE_LIST_TITLE,

   //REBOOT
   _L_REBOOT,

   //FORM STARTUP
   _L_FORM_STARTUP_MESSSAGE,
   _L_FORM_STARTUP_GOTO_SCAN_CHANNEL,
   //insert more string id here

   //FORM INFOCHANNEL
   _L_FORM_INFO_CHANNEL_TITTLE,
   _L_FORM_INFO_CHANNEL_NAME,
   _L_FORM_INFO_CHANNEL_FREQ,
   _L_FORM_INFO_CHANNEL_NUMBER,
   _L_FORM_INFO_CHANNEL_SERVICE_ID,
   _L_FORM_INFO_CHANNEL_NETWORK_ID,
   _L_FORM_INFO_CHANNEL_TUNER_STATUS,
   _L_FORM_INFO_CHANNEL_TUNER_NONE,
   _L_FORM_INFO_CHANNEL_TUNER_UNLOCKED,
   _L_FORM_INFO_CHANNEL_TUNER_LOCKED,
   _L_FORM_INFO_CHANNEL_TUNER_IDLE,
   _L_FORM_INFO_CHANNEL_TUNER_STANDBY,
   _L_FORM_INFO_CHANNEL_TUNER_SCANNING,

   //FORM PIP CONTROL
   _L_FORM_PIP_CONTROL_TITTLE,
   _L_FORM_PIP_CONTROL_CHANN,
   _L_FORM_PIP_CONTROL_CLOSE,
   _L_FORM_PIP_CONTROL_OUTPUT,
   _L_FORM_PIP_CONTROL_POS,
   _L_FORM_PIP_CONTROL_SWAP,
   _L_FORM_PIP_OUTPUT_HDMI,
   _L_FORM_PIP_OUTPUT_AV,
   _L_FORM_PIP_OUTPUT_ALL,
   _L_FORM_PIP_CONTROL_POS_TOPLEFT,
   _L_FORM_PIP_CONTROL_POS_TOPRIGHT,
   _L_FORM_PIP_CONTROL_POS_BOTLEFT,
   _L_FORM_PIP_CONTROL_POS_BOTRIGHT,
   _L_FORM_ERROR_PIP_IN_PROGRESS,
   _L_FORM_PIP_CONTROL_SWAP_WARNING_PLAYBACK,
   _L_FORM_PIP_CONTROL_OPEN_PLAYING_CHANNEL,
   _L_FORM_PIP_CONTROL_OPEN_PIP_CHANNEL,
   _L_FORM_PIP_CONTROL_NO_SIGNAL_FOUND,
   _L_FORM_PIP_CONTROL_OPEN_AUDIO_CHANNEL,
   _L_FORM_PIP_CONTROL_SWAP_AUDIO_CHANNEL,
   _L_FORM_PIP_CONTROL_DUAL_TV,
   _L_FORM_PIP_CONTROL_CLOSE_DUAL_TV,
   _L_FORM_ERROR_DUAL_TV_IN_PROGRESS,

   //FORM_CHANNEL_LOCK_CONTROL
   _L_FORM_CHANNEL_LOCK_CONTROL_TITTLE,
   _L_FORM_CHANNEL_LOCK_CONTROL_TYPE,
   _L_FORM_CHANNEL_LOCK_CONTROL_START,
   _L_FORM_CHANNEL_LOCK_CONTROL_END,
   _L_FORM_CHANNEL_LOCK_CONTROL_LOCK,
   _L_FORM_CHANNEL_LOCK_CONTROL_UNLOCK,
   _L_FORM_CHANNEL_LOCK_CONTROL_ALL,
   _L_FORM_CHANNEL_LOCK_CONTROL_EDIT,

   //FRONT PANEL
   _L_FRONT_PANEL_POWER_OFF,
   _L_FRONT_PANEL_ADJUST_VOLUME,
   _L_FRONT_PANEL_SCAN_AUTO,

   //DVR PLAYING
   _L_PLAYING_SPEED_UP,
   _L_PLAYING_SPEED_DOWN,
   _L_PLAYING_CHANGE_LOOP,
   _L_OPEN_PLAYBACK_LIST,

   //DEMO VERSION
   _L_DEMO_VERSION,
   _L_DEMO_VERSION_TIME_REACHED,

   // always put this at the bottom
   LANGUAGE_ITEM_COUNT
}
GIDCs;

#define _L_ GLanguage::getInstance()
#define NEED_CONVERT_VIETNAMESE_STRING 1

//namespace GBS {
//namespace STM {
//namespace Framework {
//////////////////////////////////////////////////////////////////////////////////////

class GLanguage
{
private:
   int m_curLanguage;
   std::string** m_ppLanguages;

   GLanguage();
   ~GLanguage();

public:
   static GLanguage& getInstance();

#ifdef NEED_CONVERT_VIETNAMESE_STRING

   static bool VN_Convert(const char* pInChar, char*& pOutChar);
   static bool VN_ConvertUTF8(const char* pInChar, char*& pOutChar);

#endif // of #ifdef NEED_CONVERT_VIETNAMESE_STRING

   int getCurrentLanguage();
   void setCurrentLanguage(int lang);

   const char* operator[](int i);
   const char* operator()(int lang, int i);
   const char* getStr(int i);
   const char* getStr(int lang, int i);

   void Initialize();
   void Initialize_VN(std::string* l);
   void Initialize_EN(std::string* l);
};

//////////////////////////////////////////////////////////////////////////////////////
//} //Framework
//} //STM
//} //GBS
#endif // GLANGUAGE_HPP_
